### ISSUE TITLE
Encourage setting read/write repo only as an upstream

### ISSUE THREAD

**Issue by yzgyyang** [bsdimp/freebsd-git-docs#27]
Do we want to encourage not setting the read/write repo as `origin`, only as `upstream` or `freebsd` or some other name? I have personally find it safer and useful to do so, with:

```
$ git remote -v
origin  anongit@git.freebsd.org (fetch)
origin  anongit@git.freebsd.org (push)
staging  git@github.com:yzgyyang/freebsd-doc.git (fetch)
staging  git@github.com:yzgyyang/freebsd-doc.git (push)
prod        git@gitrepo.FreeBSD.org:doc.git (fetch)
prod        git@gitrepo.FreeBSD.org:doc.git (push)
```

It saved me some troubles in the past, as I have to explicitly state `git push prod main` in order to commit to FreeBSD. I also like to have my own `staging` so that I can preserve my work somewhere, before branching is allowed.

**Comment by bsdimp** [comment]
I like this idea. How / where would we roll that into this document...

and how can we expand the doc document to cover src too...

**Comment by bsdimp** [comment]
Will adopt 'freebsd' as the upstream name

**Comment by yzgyyang** [comment]
> I like this idea. How / where would we roll that into this document...

I see that you made the initial commit here https://github.com/bsdimp/freebsd-git-docs/commit/c41c88ceb796d01b24e1bc21ec121e46c92b483c. I generally liked the way how SVN Primer is formed, that is, try to be consistent with the upstream name in all commands (already done in the commit mentioned above), as well as providing detailed explanation of why in a `<note>` paragraph.

I think we can further document a TL;DR version, that serves as a checklist and consists only 3 parts (I could draft it if you want):
- Must-dos during first-time setup, like setting up `git config user.{name, email}`
- Best practices, like setting R/W repo as an upstream and adding `--ff-only` to default, and why
- Common mistakes and ways to recover

> and how can we expand the doc document to cover src too...

I guess we just have to iterate on what we have ;)

> Will adopt 'freebsd' as the upstream name

Thanks again for the change! `git push freebsd main` makes so much sense to me.

I am a bit busy this week, but I will be available shortly after, and can help with writing new chapters of the Git document ;) Please let me know if some of the above ideas make sense to you.

**Comment by bsdimp** [comment]
We've fixed this, I believe. If I missed something, a pull request or a new issue would be best.
