### ISSUE TITLE
FreeBSD's git migration is a great idea

### ISSUE THREAD

**Issue by ghost** [bsdimp/freebsd-git-docs#39]
Just wanted to encourage you all and say that I'm really happy about this. I've yet to contribute any code directly to FreeBSD, but this definitely makes it easier for me.

Another pro, git is a *lot* faster pulling down updates, at least I've tended to find. `svn update` on my ports tree takes some time. It's not a big deal, just another perk. I'm sure there will be some downsides, but hopefully outweighed.

**Comment by bsdimp** [comment]
Great. Looking forward to your contributions in the future. Don't hesitate to reach out with them should the need arise.
