### ISSUE TITLE
Repository references its own removed docs

### ISSUE THREAD

**Issue by mirror176** [bsdimp/freebsd-git-docs#90]
Readme now points to other documents that are no longer in this repository; likely due to being removed as they are being integrated into FreeBSD's documents.
On unrelated notes...
  articles/committers-guide 5.2.6.4 likely has a typo with "You would help locat the commit"
  Thought it was in this repository that I saw information for working with git locally for nongit projects as a workflow to manage changes but guess I was wrong as I haven't found it with my best digging; wish I could find it again though.
  Anyone know where poudriere and other tools stand for git interface changes where relevant?
  Thanks again for the documents!

**Comment by bsdimp** [comment]
You bet. I've fixed that typo already, but I appreciate it.
Not sure about git for non-git. Sounds interesting. If you think of it, please let me know where...
Poudriere already work with git as do the other tools.
