### ISSUE TITLE
FreeBSD moving to Git: Why

### ISSUE THREAD

**Issue by grahamperrin** [bsdimp/freebsd-git-docs#91]
I see https://github.com/bsdimp/freebsd-git-docs/commit/3ebc4f7e1aec90671232060548f49e42e7c83134 **however**: 

* https://github.com/bsdimp/freebsd-git-docs/#readme still begins with [FreeBSD moving to Git: Why](https://github.com/bsdimp/freebsd-git-docs/blob/main/git-why.md)

Please, am I missing something?

**Comment by ghost** [comment]
Should be fixed in #92.

**Comment by grahamperrin** [comment]
I'm quite dizzy at the moment (too dizzy to check) but thanks for the PR!

**Comment by grahamperrin** [comment]
… so, ultimately, now, where _is_ the **Why?** documentation?

From [FreeBSD Core Team 10 in Review | FreeBSD Foundation](https://freebsdfoundation.org/blog/freebsd-core-team-10-in-review/) (2020-07-27): 

> … The forthcoming report from the Git Working Group will provide the definitive rationale for this move, …

– and so on. I have no argument with the rationale :-) I'm just looking for the definitive point of reference. Thanks

**Comment by dfboyd** [comment]
https://github.com/bsdimp/freebsd-git-docs/commit/3ebc4f7e1aec90671232060548f49e42e7c83134

This commit shows:
1. they removed the file "git-why.md"
2. in the README they removed the LINK to the file "git-how.md"

**Comment by bsdimp** [comment]
https://www.youtube.com/watch?v=uj1Ricrq0bs has at least one video on the topic. I'm not sure I ever wrote a formal report. There are likely other presentations made at the time at difference conferences asl well...

**Comment by bsdimp** [comment]
Also, this repo is basically done. I should likely archive it.

**Comment by grahamperrin** [comment]
> https://www.youtube.com/watch?v=uj1Ricrq0bs …

I watched the first fifteen seconds (with no audio, because I'm too lazy to plug in headphones), I'm hooked.

Thank you :-)
